### ISSUE TITLE
Ideas: New chemistry line

### ISSUE THREAD

**Issue by Spartak1997** [Spartak1997/GregTech5.09UnofficialBuild#26]
Add new chemistry lines for coal/lignite/coke coal and for naquadah.

What you think about it? @JohannesGaessler

**Comment by JohannesGaessler** [comment]
You are not being specific enough.
What specifically do you want to change and why?

**Comment by Spartak1997** [comment]
I mean create realistic coal/cock coal processing with blast gas refining. Creating cock coal pellets in special machine and etc. I think you know what I mean.
About Naquadah. Yesterday we with Olafe told about LuV - ... tiers and he had interesting thing about naquadah processing with distil towers and etc

**Comment by Spartak1997** [comment]
![01](https://user-images.githubusercontent.com/29407630/56790883-6aac0500-680e-11e9-9150-0d5136a792f1.png)

**Comment by Spartak1997** [comment]
![16_chemicals from coke diagram ](https://user-images.githubusercontent.com/29407630/56790944-929b6880-680e-11e9-8f83-4473c2096bcc.jpg)

**Comment by Spartak1997** [comment]
![17_Coke chemical products table](https://user-images.githubusercontent.com/29407630/56790972-a8109280-680e-11e9-96ec-756d64474d1e.jpg)

**Comment by Spartak1997** [comment]
I hope these pictures can help us with create coal/coke coal processing @JohannesGaessler

**Comment by JohannesGaessler** [comment]
I suppose something like this could be done.
However, to be honest I don't think there would be much of a point.
Mining and processing Coal for energy is already not a good strategy because making Charcoal is just so much better.
Setting up machines for processing Coal would only be worthwhile if processing gave you insane energy gains.
Similarly, processing Coal for its byproducts would probably also just be a worse version of processing Oil.

**Comment by Spartak1997** [comment]
Coal refinening will has good option only on MV/HV when we add electric coke "radiator" for creation coke pellets. It would be good fuel for boilers. And add processing for gases.
I agree it's a worse version of oil chemical but now coal doesn't have a normal using until burning on boiler
